{{- if .Values.imagePullSecret.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aas-proxy.fullname" . }}-imagepullsecret
  labels:
    {{- include "aas-proxy.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
