---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aas-proxy.fullname" . }}
  labels:
    {{- include "aas-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: default
      protocol: TCP
      name: default
  selector:
    {{- include "aas-proxy.selectorLabels" . | nindent 4 }}
