version: "3.9"

services:
  consumer-control-plane:
#    build:
#      context: services/control-plane
#      args:
#        JAR: build/libs/edc.jar
    image: edc-controlplane-memory:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8191:9191" # default/control
      - "8195:9193" # data
#      - "8282" # ids
      - "5005:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/consumer-control-plane.config:/config

  consumer-data-plane:
#    build:
#      context: services/data-plane
#      args:
#        JAR: build/libs/edc.jar
    image: edc-dataplane-hashicorp-vault:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8192:9191" # default
#      - "9192" # public
      - "5006:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
     - ./config/consumer-data-plane.config:/config

  consumer-api-wrapper:
    build:
      context: services/api-wrapper
      args:
        JAR: build/libs/edc.jar
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8193:9191" # default
#      - "9192" # callback
      - "5007:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/consumer-api-wrapper.config:/config

  provider-control-plane:
#    build:
#      context: services/control-plane
#      args:
#        JAR: build/libs/edc.jar
    image: edc-controlplane-memory:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8181:9191" # default/control
      - "8184:9192" # validation
      - "8187:9193" # data
      - "5008:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/provider-control-plane.config:/config

  provider-data-plane:
#    build:
#      context: services/data-plane
#      args:
#        JAR: build/libs/edc.jar
    image: edc-dataplane-hashicorp-vault:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8182:9191" # default
      - "8183:9192" # public
      - "5009:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/provider-data-plane.config:/config

  provider-backend-service:
    build:
      context: services/backend-data-service
      args:
        JAR: build/libs/backend-data-service.jar
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8194:8080" # default
      - "5010:8090" # debugging
