version: "3.9"

services:

  consumer-api-wrapper:
    build:
      context: services/api-wrapper
      args:
        JAR: build/libs/edc.jar
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8193:9191" # default
      - "9192" # callback
      - "5007:8090" # debugging
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/consumer-api-wrapper.config:/config
    networks:
      - api-wrapper


networks:
  api-wrapper:
    driver: bridge
