version: "3.9"

services:
  consumer-control-plane:
    image: edc-controlplane-memory:latest
    ports:
#      - "8191:9191" # default/control
#      - "9192" # validation
      - "8195:9193" # data
#      - "8282" # ids
      - "5005:8090" # debugging
    networks:
      - api-wrapper
    volumes:
      - ./config/consumer-control-plane.config/configuration.properties:/app/configuration.properties
      - ./config/consumer-control-plane.config/logging.properties:/app/logging.properties
      - ./config/consumer-control-plane.config/opentelemetry.properties:/app/opentelemetry.properties

  consumer-data-plane:
    image: edc-dataplane-hashicorp-vault:latest
    ports:
#      - "8192:9191" # default
#      - "9192" # public
      - "5006:8090" # debugging
#      - "9193" # control
    networks:
      - api-wrapper
    volumes:
      - ./config/consumer-data-plane.config/configuration.properties:/app/configuration.properties
      - ./config/consumer-data-plane.config/logging.properties:/app/logging.properties
      - ./config/consumer-data-plane.config/opentelemetry.properties:/app/opentelemetry.properties

  provider-control-plane:
    image: edc-controlplane-memory:latest
    ports:
#      - "9191" # default/control
#      - "9192" # validation
      - "8187:9193" # data
#      - "8282" # ids
      - "5008:8090" # debugging
    networks:
      - api-wrapper
    volumes:
      - ./config/provider-control-plane.config/configuration.properties:/app/configuration.properties
      - ./config/provider-control-plane.config/logging.properties:/app/logging.properties
      - ./config/provider-control-plane.config/opentelemetry.properties:/app/opentelemetry.properties

  provider-data-plane:
    image: edc-dataplane-hashicorp-vault:latest
    ports:
#      - "9191" # default
      - "8183:9192" # public
      - "5009:8090" # debugging
#      - "9193" # control
    networks:
      - api-wrapper
    volumes:
      - ./config/provider-data-plane.config/configuration.properties:/app/configuration.properties
      - ./config/provider-data-plane.config/logging.properties:/app/logging.properties
      - ./config/provider-data-plane.config/opentelemetry.properties:/app/opentelemetry.properties

  provider-backend-service:
    build:
      context: services/backend-data-service
      args:
        JAR: build/libs/backend-data-service.jar
    ports:
      - "8194:8080" # default
      - "5010:8090" # debugging
    networks:
      - api-wrapper

networks:
  api-wrapper:
    driver: bridge
