version: "3.9"

services:
  consumer-control-plane:
    image: catenax_at_home_consumer-control-plane:latest
    ports:
      - "8191:9191" # default/control (/api)
      - "8193:9193" # data (/api/v1/data)
      - "5007:8090" # debugging
    expose:
      - "9192"      # validation (/validation)
      - "8282"      # ids (/api/v1/ids) 
    networks:
      - provider_catenax_at_home
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
    volumes:
      - ./config/consumer-control-plane.config:/config
      - ./certs/cert.pfx:/cert.pfx

  consumer-data-plane:
    image: catenax_at_home_consumer-data-plane:latest
    ports:
      - "8291:9191" # default (/api)
      - "5008:8090" # debugging
    expose:
      - "9192"      # public (/public)
      - "9193"      # control (/control) maybe expose
    networks:
      - provider_catenax_at_home
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
    volumes:
     - ./config/consumer-data-plane.config:/config

  api-wrapper:
    image: catenax_at_home_api-wrapper:latest    
    ports:
      - "8091:9191" # default (/api)      
      - "5005:8090" # debugging
    expose:
      - "9192"      # callback (/callback)
    networks:
      - provider_catenax_at_home
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/api-wrapper.config:/config

  consumer-aas-proxy-service:
    image: catenax_at_home_consumer-aas-proxy-service:latest    
    ports:
      - "4245:4245" # default
      - "5014:8090" # debugging
    networks:
      - provider_catenax_at_home
    environment:
      AASPROXY_REGISTRYURL: http://registry-service:4243
      AASPROXY_WRAPPERURL: http://api-wrapper:9191/api/service
      SPRING_PROFILES_ACTIVE: local,basic
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"

networks:
  provider_catenax_at_home:
    external:
      name: catenax_at_home_dataspace