---
apiVersion: v2
name: aas-proxy
description: Semantics based AAS-Proxy
home: https://github.com/catenax-ng/catenax-at-home/deployment/helm/aas-proxy
type: application
appVersion: "0.0.1"
version: 0.0.1
maintainers: []
