version: "3.9"

services:
  consumer-control-plane:
    image: ghcr.io/catenax-ng/catenax-at-home/consumer-control-plane:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8191:9191" # default
      - "8195:9193" # data
      - "5005:8090"
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/consumer-control-plane.config:/config
      - ./certs/cert.pfx:/cert.pfx

  consumer-data-plane:
    image: ghcr.io/catenax-ng/catenax-at-home/consumer-data-plane:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8192:9191" # default
      - "5006:8090"
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
     - ./config/consumer-data-plane.config:/config

  consumer-aas-proxy:
    image: ghcr.io/catenax-ng/catenax-at-home/consumer-aas-proxy-service:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "4245:4245" # default
      - "5014:8090"

  consumer-api-wrapper:
    image: ghcr.io/catenax-ng/catenax-at-home/api-wrapper:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8193:9191" # default
#      - "9192" # callback
      - "5007:8090"
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/consumer-api-wrapper.config:/config

  provider-control-plane:
    image: ghcr.io/catenax-ng/catenax-at-home/provider-control-plane:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8181:9191" # default
      - "8184:9192" # validation
      - "8187:9193" # data
      - "8282:8282" # ids port
      - "5008:8090"
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /cert.pfx
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/provider-control-plane.config:/config
      - ./certs/cert.pfx:/cert.pfx

  provider-data-plane:
    image: ghcr.io/catenax-ng/catenax-at-home/provider-data-plane:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8182:9191" # default
      - "8183:9192" # public
      - "5009:8090"
    environment:
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./config/provider-data-plane.config:/config

  provider-backend-service:
    image: ghcr.io/catenax-ng/catenax-at-home/provider-backend-service:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8194:8080" # default
      - "5010:8090"

  registry-service:
    image: ghcr.io/catenax-ng/catenax-at-home/registry:0.0.1
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    environment:
      SPRING_PROFILES_ACTIVE: local
      IDP_ISSUER_URI: ""
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:semanticsdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
    ports:
      - "4243:4243" # default
      - "5013:8090"
