name: API-Wrapper - Build PRs
on: pull_request

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: catenax-ng/catenax-at-home/consumer-api-wrapper

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 11

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: api-wrapper/services/api-wrapper
          arguments: clean build

      - name: Extract metadata (tags, labels) for container image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr

      - name: Build container image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: api-wrapper/services/api-wrapper
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JAR=build/libs/edc.jar
