# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Veracode

# run on manual trigger or once a week
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle

      - name: Build api-wrapper
        run: ./gradlew build
        working-directory: api-wrapper/services/api-wrapper

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@v1.0
        with:
          appname: 'API-Wrapper'
          createprofile: false
          filepath: 'api-wrapper/services/build/api-wrapper.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'